---
title: "Deterministic score preparation"
output: html_document
8187.36 sec elapsed
---

```{r setup, include=FALSE}
dir_data <- "D:/HOME/ekamir/scoring_medscope/data/season_trial2" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure" 
library(easyVerification)
library(verification)
library(dplyr)
library(plyr)
library(foreach)
library(iterators)
library(parallel)
library(doParallel)
no_core <- 5

```

## Loading files

We load values previously extracted and compute ensemble means (mean between runs = models), which is required to compute deterministic scores. Values are stored in 2 3 dimensionial arrays (grids+years+t), one for prevision and one for climatology.
N.B.: 831.22 sec elapsed

```{r, echo=FALSE}
for (ind in 1:8){
cl <- makeCluster(no_core)
registerDoParallel(cl)
tictoc::tic()
foreach(b=1:500, .packages="tidyverse") %dopar%  { # loop on bootstrap samples


  
  nom_ref <- paste0(indic[ind],b,"_ref.RData")
  nom_prev <- paste0(indic[ind],b,"_prev.RData")
  nom_clim <- paste0(indic[ind],b,"_clim.RData")
  
  load(file = file.path(dir_data, "extract", nom_ref))
  load(file = file.path(dir_data, "extract", nom_prev))
  load(file = file.path(dir_data, "extract", nom_clim))

  # CROSS VALIDATED ANOMALIES: we compute and save arrays of anomalies using cross validation scheme
  
  prev_anomaly <- array(NA,dim=c(ngrids,nan,nrun,ndimT))
  clim_anomaly <- array(NA,dim=c(ngrids,nan,nrun,ndimT))
  obs_anomaly <- array(NA,dim=c(ngrids,nan,ndimT))

  for (y in 1:nan){
    cv_mean_prev <- apply(array_prev[,-y,,], c(1,3,4), mean)
    cv_mean_clim <- apply(array_clim[,-y,,], c(1,3,4), mean)
    cv_mean_obs <- apply(array_obs[,-y,], c(1,3), mean)

    prev_anomaly[,y,,] <- array_prev[,y,,]-cv_mean_prev
    clim_anomaly[,y,,] <- array_clim[,y,,]-cv_mean_clim
    obs_anomaly[,y,] <- array_obs[,y,]-cv_mean_obs
    
  }
  
  # ENSEMBLE MEAN: we compute and save arrays of ensemble mean.
  # prev_mean <- array(NA,dim=c(ngrids,nan,ndimT))
  # clim_mean <- array(NA,dim=c(ngrids,nan,ndimT))
  # 
  # for (t in 1: ndimT){
  #   
  #   for (y in 1:nan){
  #     list_prev <- list()
  #     list_clim <- list()
  #     
  #     for (r in 1:nrun){
  #       
  #       list_prev[[r]] <- array_prev[,y,r,t] # loading year i value vector for run r
  #       list_clim[[r]] <- array_clim[,y,r,t]
  #     }
  #     prev_mean[,y,t] = Reduce("+", list_prev)/nrun # compute grid mean btw all models
  #     clim_mean[,y,t] = Reduce("+", list_clim)/nrun # compute grid mean btw all models
  #   }
  # }
  # 
  # nom_prev <- paste0(indic[ind],b,"_ensmean_prev.RData")
  # nom_clim <- paste0(indic[ind],b,"_ensmean_clim.RData")
  # 
  # save(prev_mean, file = file.path(dir_data, "extract", nom_prev))
  # save(clim_mean, file = file.path(dir_data, "extract", nom_clim))

  nom_prev <- paste0(indic[ind],b,"_anomaly_prev.RData")
  nom_clim <- paste0(indic[ind],b,"_anomaly_clim.RData")
  nom_obs <- paste0(indic[ind],b,"_anomaly_obs.RData")

  save(prev_anomaly, file = file.path(dir_data, "extract", nom_prev))
  save(clim_anomaly, file = file.path(dir_data, "extract", nom_clim))
  save(obs_anomaly, file = file.path(dir_data, "extract", nom_obs))
  
}
stopCluster(cl)

}

tictoc::toc() 

```





