---
title: "Mapping probabilistic scores"
output: html_document
---

```{r}
dir_data <- "D:/HOME/ekamir/scoring_medscope/data/season_trial2" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure" 
library(maps)
library(maptools)
library(rasterVis)
library(ggplot2)
library(latticeExtra)
library(sp)
library(raster)
library(rgdal)
library(tmap)
library(sf)
library(ggmap)
library(mapview)
library(grid)
```
## Parameter specifications

Indicator to be displayed
Region of interest

```{r}
moi <- c("May","June","July","August","September","October","November")
ind <- 2

ind_fr <- c("Pluie – evaporation", "Somme des pluies","Nombre de jours de pluie","Nombre de jours T max > 25°C", 
             "Nombre de jours T max > 35°C", "Moyenne T max","Moyenne T min","Moyenne T moy")
ind_eng <- c("Rain – evaporation", "Accumulated rainfall","Number of rainy days","Number of days T max > 25°C", 
             "Number of days T max > 35°C", "T max mean","T min mean","T mean mean")

```
## Loading raster

Specific to indicator and year of prevision

```{r}

title <- paste0(indic[ind],"_probsign.tif")
stacky <- stack(file.path(dir_plot, "season_raster", title)) # loading stack file

load(file = file.path(dir_plot, "season_raster", "prob_layname.RData")) # loading stack layer names before writeraster changed them
names(stacky) <- c(layername)# re setting original layer names
```
### MONTHLY MAPS ###

We create one shapefile per month from each raster layer extraction

```{r}

## CREATING SHAPEFILE TO BE PLOTTED BY EXTRACTING RASTER LAYER + FACET DISPLAYING 
tmap_mode('plot')
htshp_score <- list()
htshp_sign <- list()
maprev <- list()
grid.newpage()
page.layout <- grid.layout(nrow = 3, ncol = 3)
pushViewport(viewport(layout = page.layout))


for (m in 1:ndimT){
 
  ### we build the shapefiles of tercile scores
  ht_score <- rasterToPolygons(stacky[[4+5*(m-1)]]) 
  names(ht_score) <- "ROC.High.Tercile"
  htshp_score[[m]] <- st_as_sf(ht_score)

  ### we build the shapefile of score statistical significance 
  ht_sign <- rasterToPolygons(stacky[[5+5*(m-1)]])
  names(ht_sign) <- "highter_significance"
  ht_sign$highter_significance[which(ht_sign$highter_significance==0)] <- NA # to help plotting
  htshp_sign[[m]] <- st_as_sf(ht_sign)

  ### mapping
  titre <- paste0(ind_eng[ind]," ","score on"," ", moi[m])
  maprev [[m]]<- qtm(htshp_score[[m]], fill = "ROC.High.Tercile",
     attr.outside = TRUE,borders = NULL, fill.palette = "YlOrRd")+ 
 tm_shape(htshp_sign[[m]])+
   tm_symbols(size ="highter_significance", col = "yellow", scale = 0.1)+
 #tm_grid(y=c(43.487, 43.787), x=c(4,03,4.5,5),  labels.inside.frame = TRUE, alpha = 0, labels.rot = c(0,90))+
 #tm_scale_bar()+
     tm_layout(title = titre, title.position = c("left","bottom"), title.size = 0.5, legend.show = FALSE)

   if (m<4){
  print(maprev[[m]], vp=viewport(layout.pos.row = 1, layout.pos.col = m))
  }
  else {
  print(maprev[[m]], vp=viewport(layout.pos.row = 2, layout.pos.col = m-3))
  }

}

com_legend <- qtm(htshp_score[[m]], fill = "ROC.High.Tercile", fill.style="cont", fill.breaks=c( 0.2, 0.4, 0.6, 0.8, 1),
     attr.outside = TRUE,borders = NULL, fill.palette = "YlOrRd")+ 
     tm_layout(legend.only = TRUE)

print(com_legend, vp=viewport(layout.pos.row = 3, layout.pos.col = 2))


```
## Creating maps displaying ROC scores through ggplot package


```{r}
mappy <- list()
# grid.newpage()
# page.layout <- grid.layout(nrow = 2, ncol = 3)
# pushViewport(viewport(layout = page.layout))

### BACKGROUND LOADED FROM GOOGLE
# key = "AIzaSyCD2-pP0yfM8aC8sjCB4g--CaCcExP6NhU"; "AIzaSyB24WUzCzX1lErLgsVLtio1c7QxLfw1_SA"
# register_google(key = "AIzaSyB24WUzCzX1lErLgsVLtio1c7QxLfw1_SA")
# back_map <- get_map(location = c(1.2, 41, 10, 46), maptype = "satellite", source = "google") 

### CREATING SHAPEFILES SPECIFIC TO EACH MONTHS - 1 FOR SCORE 1 FOR VALUE SIGNIFICANCE
for (m in 1:ndimT){
  
  # shapefile of score values
  sp_score <- rasterToPolygons(stacky[[4+5*(m-1)]])
  names(sp_score) <- "score"
  shp_score[[m]] <- st_as_sf(sp_score)

  # shapefile of score value significance (wilcoxon test outcome)
  sp_sign <- rasterToPoints(stacky[[5+5*(m-1)]], spatial = TRUE)
  names(sp_sign) <- "significance"
  sp_sign$significance[which(sp_sign$significance==0)] <- NA # to help plotting
  # sp_test <- as.data.frame(sp_sign)
  sf_test <- st_as_sf(sp_sign)
  sf_nrm <- remove_missing(sf_test)
  
  sp_si <- rasterToPolygons(stacky[[3+3*(m-1)]])
  sp_pt2 <- st_as_sf(sp_si)
  sp_pt <- st_centroid(sp_pt2,byid=TRUE)
  
### OVERLAYING SHAPEFILE ON GOOGLE BACKGROUND MAP
mappy[[m]] <- ggmap(back_map) + 
  geom_sf(data = shp_score[[m]], aes(fill = score), inherit.aes = FALSE)+
  scale_fill_gradient(low = "orange", high = "green")+
  geom_sf(data = sf_nrm, aes(colour = significance), inherit.aes = FALSE, size = 0.02, show.legend = FALSE)+
  scale_colour_gradient(low = "blue", high = "blue")+
  labs(title = paste0(ind_eng[ind]," HT AUC for ", moi[m]))+
  theme(plot.title = element_text(size = 12, hjust = 0, vjust = 1.5))

}
```
