---
title: "map_prevconf"
output: html_document
---

```{r}
dir_data <- "D:/HOME/ekamir/scoring_medscope/data/season_trial2" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure" 
library(maps)
library(maptools)
library(rasterVis)
library(ggplot2)
library(latticeExtra)
library(sp)
library(raster)
library(rgdal)
library(tmap)
library(sf)
library(ggmap)
library(mapview)
library(grid)
```
## Parameter specifications

Indicator to be displayed
Month
Region of interest

```{r}
select_year <- 2000
moi <- c("May","June","July","August","September","October","November")
annees <- c(1993:2016)
ind <- 1

ind_fr <- c("Pluie – evaporation", "Somme des pluies","Nombre de jours de pluie","Nombre de jours T max > 25°C", 
             "Nombre de jours T max > 35°C", "Moyenne T max","Moyenne T min","Moyenne T moy")
ind_eng <- c("Rain – evaporation", "Accumulated rainfall","Number of rainy days","Number of days T max > 25°C", 
             "Number of days T max > 35°C", "T max mean","T min mean","T mean mean")

```
## Loading raster

Specific to indicator and year of prevision

```{r}

title <- paste0(indic[ind],"_confprev", select_year,".tif")
stacky <- stack(file.path(dir_plot, "season_raster", title)) # loading stack file

```
## Creating maps displaying prevision and skill shapefiles

We create one shapefile per month from each raster layer extraction

```{r}

## CREATING SHAPEFILE TO BE PLOTTED BY EXTRACTING RASTER LAYER + FACET DISPLAYING 
tmap_mode('plot')
shp_tercile <- list()
shp_conf <- list()
maprev <- list()
grid.newpage()
page.layout <- grid.layout(nrow = 3, ncol = 3)
pushViewport(viewport(layout = page.layout))


for (m in 1:ndimT){
 
  ### we build the shapefile of most likely tercile 
  sp_tercile <- rasterToPolygons(stacky[[2+3*(m-1)]]) 
  names(sp_tercile) <- "tercile"
  shp_tercile[[m]] <- st_as_sf(sp_tercile)

  ### we build the shapefile of prevision confidence
  sp_conf <- rasterToPolygons(stacky[[3+3*(m-1)]])
  names(sp_conf) <- "confidence"
  sp_conf$confidence[which(sp_conf$confidence==0)] <- NA # to help plotting
  shp_conf[[m]] <- st_as_sf(sp_conf)
  
   
#    1st tercile = lower tercile; 2nd = middle; 3rd = upper
  
  ### mapping
  titre <- paste0(ind_eng[ind]," ","for"," ", moi[m], " ", select_year)
  maprev [[m]]<- qtm(shp_tercile[[m]], fill = "tercile",
     attr.outside = TRUE,borders = NULL, fill.style="fixed",fill.breaks=c(1,2,3,4), fill.palette = c("darkslategray2","lightgrey","dodgerblue3"), legend.fill.show=FALSE)+ 
 tm_shape(shp_conf[[m]])+
   tm_symbols(size ="confidence", col = "yellow", scale = 0.1)+
 #tm_grid(y=c(43.487, 43.787), x=c(4,03,4.5,5),  labels.inside.frame = TRUE, alpha = 0, labels.rot = c(0,90))+
 #tm_scale_bar()+
 tm_add_legend(type = "fill", labels = c("3rd tercile","2nd tercile","1st tercile"), col =  c("dodgerblue3","lightgrey","darkslategray2"), alpha = 0.5)+
     tm_layout(title = titre, title.position = c("left","bottom"), title.size = 0.5, legend.show = FALSE)

   if (m<4){
  print(maprev[[m]], vp=viewport(layout.pos.row = 1, layout.pos.col = m))
  }
  else {
  print(maprev[[m]], vp=viewport(layout.pos.row = 2, layout.pos.col = m-3))
  }

}

com_legend <- qtm(shp_tercile[[m]], fill = "tercile",
     attr.outside = TRUE,borders = NULL, fill.style="fixed",fill.breaks=c(1,2,3,4), fill.palette = c("darkslategray2","lightgrey","dodgerblue3"))+  
     tm_layout(legend.only = TRUE)

print(com_legend, vp=viewport(layout.pos.row = 3, layout.pos.col = 2))


```
