---
title: "Mapping AUC for upper decile"
output: html_document
---

```{r}

dir_data <- "D:/HOME/ekamir/scoring_medscope/data/season_trial2" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure" 

library(maps)
library(maptools)
library(rasterVis)
library(ggplot2)
library(latticeExtra)
library(sp)
library(raster)
library(rgdal)
library(tmap)
library(sf)
library(ggmap)
library(mapview)
library(grid)

```
## Parameter specifications

Indicator to be displayed
Region of interest

```{r}

moi <- c("May","June","July","August","September","October","November")
ind_fr <- c("Pluie – evaporation", "Somme des pluies","Nombre de jours de pluie","Nombre de jours T max > 25°C", 
             "Nombre de jours T max > 35°C", "Moyenne T max","Moyenne T min","Moyenne T moy")
ind_eng <- c("Rain – evaporation", "Accumulated rainfall","Number of rainy days","Number of days T max > 25°C", 
             "Number of days T max > 35°C", "T max mean","T min mean","T mean mean")

```
## Loading raster

Specific to indicator and year of prevision

```{r}
ind <- 3

title <- paste0(indic[ind],"_seasondecile.tif")
stack_seas <- stack(file.path(dir_plot, "season_raster", title)) # loading stack file

load(file = file.path(dir_plot, "season_raster", "decileseas_layname.RData")) # loading stack layer names before writeraster changed them
names(stack_seas) <- c(layername)# re setting original layer names

if (ind!=3 & ind!=4 & ind!=5) {
  title <- paste0(indic[ind],"_monthdecile.tif")
  stack_month <- stack(file.path(dir_plot, "season_raster", title)) # loading stack file
  load(file = file.path(dir_plot, "season_raster", "decilemonth_layname.RData")) # loading stack layer names before writeraster changed them
  names(stack_month) <- c(layername)# re setting original layer names
}

temp_ggplot <- c("#fee0d2", "#fc9272", "#de2d26")
score_palette <- c("#d7191c","#f4a582","#ffffbf","#abd9e9","#2c7bb6")

```
### MONTHLY MAPS ###

We create one shapefile per month from each raster layer extraction

```{r}

## CREATING SHAPEFILE TO BE PLOTTED BY EXTRACTING RASTER LAYER + FACET DISPLAYING 
tmap_mode('plot')
ldshp_score <- list()
ldshp_sign <- list()
maprev <- list()
grid.newpage()
page.layout <- grid.layout(nrow = 3, ncol = 3)
pushViewport(viewport(layout = page.layout))


for (m in 1:ndimT){
  
  ### we build the shapefiles of tercile scores
  ld_score <- rasterToPolygons(stack_month[[2+5*(m-1)]]) 
  names(ld_score) <- "AUC.Low.Decile"
  ld_score$AUC.Low.Decile[which(ld_score$AUC.Low.Decile==-1)] <- NA # to help plotting
  ldshp_score[[m]] <- st_as_sf(ld_score)
  
  ### we build the shapefile of score statistical significance 
  ld_sign <- rasterToPolygons(stack_month[[3+5*(m-1)]])
  names(ld_sign) <- "lowdec_significance"
  ld_sign$lowdec_significance[which(ld_sign$lowdec_significance==0)] <- NA # to help plotting
  ld_sign$lowdec_significance[which(ld_sign$lowdec_significance==-1)] <- NA # to help plotting
  ldshp_sign[[m]] <- st_as_sf(ld_sign)
  
  ### mapping
  titre <- paste0(ind_eng[ind]," ","score on"," ", moi[m])
  maprev [[m]]<- qtm(ldshp_score[[m]], fill = "AUC.Low.Decile",
                     fill.style="cont", fill.breaks=c(seq(0, 1, length.out = 6)),borders = NULL, fill.palette = score_palette)+ 
    tm_shape(ldshp_sign[[m]])+
    tm_symbols(size ="lowdec_significance", col = "yellow", scale = 0.02)+
    #tm_grid(y=c(43.487, 43.787), x=c(4,03,4.5,5),  labels.inside.frame = TRUE, alpha = 0, labels.rot = c(0,90))+
    #tm_scale_bar()+
    tm_layout(title = titre, title.position = c("left","bottom"), title.size = 0.5, legend.show = FALSE)
  
  if (m<4){
    print(maprev[[m]], vp=viewport(layout.pos.row = 1, layout.pos.col = m))
  }
  else {
    print(maprev[[m]], vp=viewport(layout.pos.row = 2, layout.pos.col = m-3))
  }
  
}

com_legend <- qtm(ldshp_score[[m]], fill = "AUC.Low.Decile", fill.style="cont", fill.breaks=c(seq(0, 1, length.out = 6)),
                  attr.outside = TRUE,borders = NULL, fill.palette = score_palette)+ 
  tm_layout(legend.only = TRUE)

print(com_legend, vp=viewport(layout.pos.row = 3, layout.pos.col = 2))


```

### SEASON MAPS ###



```{r}

### BACKGROUND LOADED FROM GOOGLE
# key = "AIzaSyCD2-pP0yfM8aC8sjCB4g--CaCcExP6NhU"; "AIzaSyB24WUzCzX1lErLgsVLtio1c7QxLfw1_SA"
# register_google(key = "AIzaSyB24WUzCzX1lErLgsVLtio1c7QxLfw1_SA")
# back_map <- get_map(location = c(1.2, 41, 10, 46), maptype = "satellite", source = "google") 

  sp_roc <- rasterToPolygons(stack_seas[[4]]) 
  names(sp_roc) <- "AUC.Low.Decile"
  sp_roc$AUC.Low.Decile[which(sp_roc$AUC.Low.Decile==-1)] <- NA # to help plotting
  shp_roc <- st_as_sf(sp_roc)

  # shapefile of prevision confidence
  sp_sign <- rasterToPoints(stack_seas[[5]], spatial = TRUE)
  names(sp_sign) <- "significance"
  sp_sign$significance[which(sp_sign$significance==0)] <- NA # to help plotting
  sp_sign$significance[which(sp_sign$significance==-1)] <- NA # to help plotting
  sf_test <- st_as_sf(sp_sign)
  sf_nrm <- remove_missing(sf_test)
  
  sp_si <- rasterToPolygons(stack_seas[[3]])
  sp_pt2 <- st_as_sf(sp_si)
  sp_pt <- st_centroid(sp_pt2,byid=TRUE)
  
  shp_tercile$tercile <- as.factor(shp_tercile$tercile)
  
### OVERLAYING SHAPEFILE ON GOOGLE BACKGROUND MAP
ggmap(back_map) + 
  geom_sf(data = shp_roc, aes(fill = AUC.Low.Decile), inherit.aes = FALSE, alpha = 1)+
  continuous_scale(aesthetics = "AUC.Low.Decile", scale_name = "manual", palette = 0.3)+
  scale_fill_gradientn(colours=score_palette, limits = c(0,1))+ 
  geom_sf(data = sf_nrm, aes(colour = significance), inherit.aes = FALSE, size = 0.02, show.legend = FALSE)+
  labs(title = paste0(" Season score - ", ind_eng[ind]))+
  theme(plot.title = element_text(size = 12, hjust = 0, vjust = 1.5))


```
