---
title: "Mapping AUC for upper quintile"
output: html_document
---

```{r}

dir_data <- "D:/HOME/ekamir/scoring_medscope/data/season_trial2" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure" 

library(maps)
library(maptools)
library(rasterVis)
library(ggplot2)
library(latticeExtra)
library(sp)
library(raster)
library(rgdal)
library(tmap)
library(sf)
library(ggmap)
library(mapview)
library(grid)

```
## Parameter specifications

Indicator to be displayed
Region of interest

```{r}

moi <- c("May","June","July","August","September","October","November")
ind_fr <- c("Pluie – evaporation", "Somme des pluies","Nombre de jours de pluie","Nombre de jours T max > 25°C", 
             "Nombre de jours T max > 35°C", "Moyenne T max","Moyenne T min","Moyenne T moy")
ind_eng <- c("Rain – evaporation", "Accumulated rainfall","Number of rainy days","Number of days T max > 25°C", 
             "Number of days T max > 35°C", "T max mean","T min mean","T mean mean")

```
## Loading raster

Specific to indicator and year of prevision

```{r}
ind <- 8

title <- paste0(indic[ind],"_seasonHQauc.tif")
stack_seas <- stack(file.path(dir_plot, "season_raster", title)) # loading stack file

temp_ggplot <- c("#fee0d2", "#fc9272", "#de2d26")
score_palette <- c("#d7191c","#f4a582","#ffffbf","#abd9e9","#2c7bb6")

```

### SEASON MAPS ###



```{r}

### BACKGROUND LOADED FROM GOOGLE
# key = "AIzaSyCD2-pP0yfM8aC8sjCB4g--CaCcExP6NhU"; "AIzaSyB24WUzCzX1lErLgsVLtio1c7QxLfw1_SA"
# register_google(key = "AIzaSyB24WUzCzX1lErLgsVLtio1c7QxLfw1_SA")
# back_map <- get_map(location = c(1.2, 41, 10, 46), maptype = "satellite", source = "google") 

  sp_roc <- rasterToPolygons(stack_seas[[2]]) 
  names(sp_roc) <- "AUC.High.Quint"
  sp_roc$AUC.High.Quint[which(sp_roc$AUC.High.Quint==-1)] <- NA # to help plotting
  shp_roc <- st_as_sf(sp_roc)

  # shapefile of prevision confidence
  sp_sign <- rasterToPoints(stack_seas[[3]], spatial = TRUE)
  names(sp_sign) <- "significance"
  sp_sign$significance[which(sp_sign$significance==0)] <- NA # to help plotting
  sp_sign$significance[which(sp_sign$significance==-1)] <- NA # to help plotting
  sf_test <- st_as_sf(sp_sign)
  sf_nrm <- remove_missing(sf_test)
  
  # sp_si <- rasterToPolygons(stack_seas[[3]])
  # sp_pt2 <- st_as_sf(sp_si)
  # sp_pt <- st_centroid(sp_pt2,byid=TRUE)
  
  shp_tercile$tercile <- as.factor(shp_tercile$tercile)
  
### OVERLAYING SHAPEFILE ON GOOGLE BACKGROUND MAP
ggmap(back_map) + 
  geom_sf(data = shp_roc, aes(fill = AUC.High.Quint), inherit.aes = FALSE, alpha = 1)+
  continuous_scale(aesthetics = "AUC.High.Quint", scale_name = "manual", palette = 0.3)+
  scale_fill_gradientn(colours=score_palette, limits = c(0,1))+ 
  geom_sf(data = sf_nrm, aes(colour = significance), inherit.aes = FALSE, size = 0.02, show.legend = FALSE)+
  labs(title = paste0(" Season score - ", ind_eng[ind]))+
  theme(plot.title = element_text(size = 12, hjust = 0, vjust = 1.5))


```
