---
title: "Mapping deterministic scores"
output: html_document
---

```{r}

dir_data <- "D:/HOME/ekamir/scoring_medscope/data/season_trial2" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure" 

library(maps)
library(maptools)
library(tmaptools)
library(rasterVis)
library(ggplot2)
library(latticeExtra)
library(sp)
library(raster)
library(rgdal)
library(tmap)
library(sf)
library(ggmap)
library(mapview)
library(grid)
library(ggpubr)
library(rgeos)
```
## Parameter specifications

Indicator to be displayed
Region of interest

```{r}
moi <- c("May","June","July","August","September","October","November")
ind <- 3

ind_fr <- c("Pluie – evaporation", "Somme des pluies","Nombre de jours de pluie","Nombre de jours T max > 25°C", 
             "Nombre de jours T max > 35°C", "Moyenne T max","Moyenne T min","Moyenne T moy")
ind_eng <- c("Rain – evaporation", "Accumulated rainfall","Number of rainy days","Number of days T max > 25°C", 
             "Number of days T max > 35°C", "T max mean","T min mean","T mean mean")

```
### LOADING RASTER FILES ###


```{r}
title <- paste0(indic[ind],"_detseas",".tif")
stacky_seas <- stack(file.path(dir_plot, "season_raster", title)) # loading stack file

if (ind!=3 & ind!=4 & ind!=5) { 
  title <- paste0(indic[ind],"_detmonth",".tif")
  stacky_mois <- stack(file.path(dir_plot, "season_raster", title)) # loading stack file
  load(file = file.path(dir_plot, "season_raster", "layname_detmonth.RData")) # loading stack layer names before     writeraster changed them
  names(stacky_mois) <- c(layername)# re setting original layer names

}


load(file = file.path(dir_plot, "season_raster", "layname_detseas.RData")) # loading stack layer names before writeraster changed them
names(stacky_seas) <- c(layername)# re setting original layer names

score_palette <- c("#ca0020","#f4a582","#f7f7f7","#92c5de","#0571b0")
```
### MONTHLY MAPS ###

Continuous indicators only
We create one shapefile per month from each raster layer extraction

```{r}
large_breaks <- c(-3e-04, 3e-04)
rain_breaks <- c(-0.01, 0.01)
temp_breaks <- c(-0.0003, 0.0003)
day25 <- c(-0.0015, 0.0015)
drain <- c(-0.002, 0.002)

## CREATING SHAPEFILE TO BE PLOTTED BY EXTRACTING RASTER LAYER + FACET DISPLAYING 
tmap_mode('plot')
shp_sign <- list()
shp_score <- list()
maprev <- list()
grid.newpage()
page.layout <- grid.layout(nrow = 3, ncol = 3)
pushViewport(viewport(layout = page.layout))


for (m in 1:ndimT){
  
  ### we build the shapefile of most likely tercile 
  sp_score <- rasterToPolygons(stacky_mois[[2+3*(m-1)]]) 
  names(sp_score) <- "MSESS"
  shp_score[[m]] <- st_as_sf(sp_score)
  
  ### we build the shapefile of most likely tercile 
  sp_sign <- rasterToPolygons(stacky_mois[[3+3*(m-1)]])
  names(sp_sign) <- "significance"
  sp_sign$significance[which(sp_sign$significance==0)] <- NA # to help plotting
  shp_sign[[m]] <- st_as_sf(sp_sign)
  
  ### mapping
  titre <- paste0(ind_eng[ind]," ","MSESS on"," ", moi[m])
  
  maprev [[m]]<- 
    tm_shape(shp_score[[m]])+
    tm_fill(col = "MSESS", style="cont", breaks = seq(-3e-04, 3e-04, length.out = 8), 
            attr.outside = TRUE, borders = NULL, palette = score_palette)+ 
    tm_shape(shp_sign[[m]])+
    tm_symbols(size ="significance", col = "yellow", scale = 0.05)+
    #tm_grid(y=c(43.487, 43.787), x=c(4,03,4.5,5),  labels.inside.frame = TRUE, alpha = 0, labels.rot = c(0,90))+
    #tm_scale_bar()+
    tm_layout(title = titre, title.position = c("left","bottom"), title.size = 0.5, legend.show = FALSE)
  
  if (m<4){
    print(maprev[[m]], vp=viewport(layout.pos.row = 1, layout.pos.col = m))
  }
  else {
    print(maprev[[m]], vp=viewport(layout.pos.row = 2, layout.pos.col = m-3))
  }
  
}

com_legend <- qtm(shp_score[[m]], fill = "MSESS", fill.style="cont", attr.outside = TRUE, borders = NULL, fill.palette = score_palette,
                  fill.breaks = seq(-3e-04, 3e-04, length.out = 8))+ 
  tm_layout(legend.only = TRUE)+
  tmap_options()

print(com_legend, vp=viewport(layout.pos.row = 3, layout.pos.col = 2))

### trial: adding background map
# tm_shape(ras_prev_complete$tercile)+
#   tm_raster()

```
### SEASON MAPS ###


```{r}
large_breaks <- c(-3e-04, 3e-04)
rain_breaks <- c(-0.3, 0.3)
temp_breaks <- c(-0.4, 0.4)
day25 <- c(-0.6, 0.6)
drain <- c(-0.5, 0.5)

### BACKGROUND LOADED FROM GOOGLE
# key = "AIzaSyCD2-pP0yfM8aC8sjCB4g--CaCcExP6NhU"; "AIzaSyB24WUzCzX1lErLgsVLtio1c7QxLfw1_SA"
# register_google(key = "AIzaSyB24WUzCzX1lErLgsVLtio1c7QxLfw1_SA")
# back_map <- get_map(location = c(1.2, 41, 10, 46), maptype = "satellite", source = "google") 

  sp_msess <- rasterToPolygons(stacky_seas[[2]]) 
  names(sp_msess) <- "msess"
  shp_msess <- st_as_sf(sp_msess)

  # shapefile of prevision confidence
  sp_sign <- rasterToPoints(stacky_seas[[3]], spatial = TRUE)
  names(sp_sign) <- "significance"
  sp_sign$significance[which(sp_sign$significance==0)] <- NA # to help plotting
  sf_test <- st_as_sf(sp_sign)
  sf_nrm <- remove_missing(sf_test)
  
  sp_si <- rasterToPolygons(stacky_seas[[3]])
  sp_pt2 <- st_as_sf(sp_si)
  sp_pt <- st_centroid(sp_pt2,byid=TRUE)
  
  shp_tercile$tercile <- as.factor(shp_tercile$tercile)
### OVERLAYING SHAPEFILE ON GOOGLE BACKGROUND MAP
ggmap(back_map) +
  geom_sf(data = shp_msess, aes(fill = msess), inherit.aes = FALSE, alpha = 1)+
  continuous_scale(aesthetics = "msess", scale_name = "manual", palette = 0.1)+
  scale_fill_gradientn(colours=score_palette)+ #, limits = drain , limits = day25
  geom_sf(data = sf_nrm, aes(colour = significance), inherit.aes = FALSE, size = 0.02, show.legend = FALSE)+
  labs(title = paste0(ind_eng[ind]," season MSESS "))+
  theme(plot.title = element_text(size = 12, hjust = 0, vjust = 1.5))

```
