---
title: "mapping_prev"
output: html_document
---

```{r}
dir_data <- "D:/HOME/ekamir/scoring_medscope/data/season_trial2" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure" 
library(maps)
library(maptools)
library(rasterVis)
library(ggplot2)
library(latticeExtra)
library(sp)
library(raster)
library(rgdal)
library(tmap)
library(sf)
library(ggmap)
library(mapview)
library(grid)
```
## Parameter specifications

Indicator to be displayed
Month
Region of interest

```{r}
#ind <- 2
select_year <- 2005
moi <- c("May","June","July","August","September","October","November")
annees <- c(1993:2016)
ind <- 2

ind_fr <- c("Pluie – evaporation", "Somme des pluies","Nombre de jours de pluie","Nombre de jours T max > 25°C", 
             "Nombre de jours T max > 35°C", "Moyenne T max","Moyenne T min","Moyenne T moy")
ind_eng <- c("Rain – evaporation", "Accumulated rainfall","Number of rainy days","Number of days T max > 25°C", 
             "Number of days T max > 35°C", "T max mean","T min mean","T mean mean")

```
## Loading raster

Specific to indicator and year of prevision

```{r}
load(file = file.path(dir_plot, "season_raster", "layname.RData")) # loading stack layer names before writeraster changed them

title <- paste0(indic[ind],"_prevskill", select_year,".tif")
stacky <- stack(file.path(dir_plot, "season_raster", title)) # loading stack file

names(stacky) <- c(layername)# re setting original layer names
```
## Creating maps displaying prevision and skill shapefiles

We create one shapefile per month from each raster layer extraction

```{r}

## CREATING SHAPEFILE TO BE PLOTTED BY EXTRACTING RASTER LAYER + FACET DISPLAYING 
tmap_mode('plot')
shp_tercile <- list()
shp_wilcox <- list()
maprev <- list()
grid.newpage()
page.layout <- grid.layout(nrow = 2, ncol = 3)
pushViewport(viewport(layout = page.layout))


for (m in 1:ndimT){
 
  ### we build the shapefile of most likely tercile 
  sp_tercile <- rasterToPolygons(stacky[[2+3*(m-1)]]) 
  names(sp_tercile) <- "tercile"
  shp_tercile[[m]] <- st_as_sf(sp_tercile)

  ### we build the shapefile of most likely tercile 
  sp_wilcox <- rasterToPolygons(stacky[[3+3*(m-1)]])
  names(sp_wilcox) <- "wilcoxon"
  sp_wilcox$wilcoxon[which(sp_wilcox$wilcoxon==0)] <- NA # to help plotting only high confidence dots
  sp_wilcox$wilcoxon[which(sp_wilcox$wilcoxon==2)] <- NA # to help plotting only high confidence dots #  TO BE CHANGEDDDD
  shp_wilcox[[m]] <- st_as_sf(sp_wilcox)
  
   
#    1st tercile = lower tercile
  #
  ### mapping
  titre <- paste0(ind_eng[ind]," ","for"," ", moi[m], " ", select_year)
  maprev [[m]]<- tm_basemap(leaflet::providers$Esri.WorldTopoMap)+ 
    qtm(shp_tercile[[m]], fill = "tercile", fill.legend.show = FALSE,
     attr.outside = TRUE,borders = NULL, fill.style="fixed",fill.breaks=c(1,2,3,4), fill.palette = c("darkslategray2","lightgrey","dodgerblue3"))+ 
 tm_shape(shp_wilcox[[m]])+
   tm_symbols(size ="wilcoxon", col = "yellow", legend.size.show = FALSE, scale = 0.1)+
 #tm_grid(y=c(43.487, 43.787), x=c(4,03,4.5,5),  labels.inside.frame = TRUE, alpha = 0, labels.rot = c(0,90))+
 tm_scale_bar()+
 tm_add_legend(type = "fill", labels = c("3rd tercile","2nd tercile","1st tercile"), col =  c("dodgerblue3","lightgrey","darkslategray2"), alpha = 0.5)+
     tm_layout(title = titre, title.position = c("left","bottom"), title.size = 0.5)
    

   if (m<4){
  print(maprev[[m]], vp=viewport(layout.pos.row = 1, layout.pos.col = m))
  }
  else {
  print(maprev[[m]], vp=viewport(layout.pos.row = 2, layout.pos.col = m-3))
  }

}


```
## Interactive mapping


```{r}
tmap_mode('view')

############# SINGLE MAP ##################

### we build the shapefile of most likely tercile 
#   sp_tercile <- rasterToPolygons(stacky[[2+3*(t-1)]]) 
#   names(sp_tercile) <- "tercile"
#   shp_tercile <- st_as_sf(sp_tercile)
# 
#   ### we build the shapefile of most likely tercile 
#   sp_wilcox <- rasterToPolygons(stacky[[3+3*(t-1)]])
#   names(sp_wilcox) <- "wilcoxon"
#   sp_wilcox$wilcoxon[which(sp_wilcox$wilcoxon==0)] <- NA # to help plotting only high confidence dots
#   shp_wilcox <- st_as_sf(sp_wilcox)
# 
# 

 
  
  # title = titrei, main.title.position = c("")
  # map2 <- qtm(shp_tercile, fill = "tercile",
  #                fill.style="fixed",fill.breaks=c(1,2,3), fill.palette = c("darkslategray2", "dodgerblue3"), borders = NULL, fill.alpha=0, fill.legend.show = FALSE)+  
  # tm_shape(shp_tercile)+
  # tm_fill(col ="tercile", alpha=0.6, palette = c("darkslategray2", "dodgerblue3"), legend.show = FALSE)+
  #    tm_shape(shp_wilcox)+
  #       tm_symbols(size ="wilcoxon", col = "red", alpha=1, scale = 0.3)+
  # tm_scale_bar()+
  # tm_add_legend(type = "fill", labels = c("Upper tercile", "Lower tercile"), col = c("dodgerblue3","darkslategray2"))+
  #    tm_layout(title = titrei, title.position = c("left","bottom"), title.size = 0.5)


  ############# MULTI MAPS ##################

shp_tercile <- list()
shp_wilcox <- list()
maprev <- list()
for (m in 1:ndimT){
 
  ### we build the shapefile of most likely tercile 
  sp_tercile <- rasterToPolygons(stacky[[2+3*(m-1)]]) 
  names(sp_tercile) <- "tercile"
  shp_tercile[[m]] <- st_as_sf(sp_tercile)

  ### we build the shapefile of most likely tercile 
  sp_wilcox <- rasterToPolygons(stacky[[3+3*(m-1)]])
  names(sp_wilcox) <- "wilcoxon"
  sp_wilcox$wilcoxon[which(sp_wilcox$wilcoxon==0)] <- NA # to help plotting only high confidence dots
  sp_wilcox$wilcoxon[which(sp_wilcox$wilcoxon==2)] <- NA # to help plotting only high confidence dots
  shp_wilcox[[m]] <- st_as_sf(sp_wilcox)
  
  ### mapping
  titre <- paste0(ind_eng[ind]," ","for"," ", moi[m], " ", select_year)
#
  maprev[[m]] <- qtm(shp_tercile[[m]], fill = "tercile",fill.style="fixed",fill.breaks=c(1,2,3,4),
                  fill.palette = c("darkslategray2","yellow", "dodgerblue3"), borders = NULL, fill.alpha=0, fill.legend.show = FALSE)+  
  tm_shape(shp_tercile[[m]],fill.style="fixed",fill.breaks=c(1,2,3,4))+
  tm_fill(col ="tercile", alpha=0.6, palette = c("darkslategray2","lightgrey", "dodgerblue3"), legend.show = FALSE)+
     tm_shape(shp_wilcox[[m]])+
        tm_symbols(size ="wilcoxon", col = "red", alpha=1, scale = 0.3)+
  tm_scale_bar()+
  tm_add_legend(title = titre, type = "fill", labels = c("3rd tercile","2nd tercile","1st tercile"), col = c("dodgerblue3","lightgrey","darkslategray2"))

}
tmap_options(limits = c(facets.view = 6))
tmap_arrange(maprev[[1]],maprev[[2]],maprev[[3]],maprev[[4]],maprev[[5]],maprev[[6]])
 
```
