---
title: "raster_prevconf"
output: html_document
---

```{r}

dir_data <- "D:/HOME/ekamir/scoring_medscope/data/season_trial2" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure" 

library(maps)
library(maptools)
library(rasterVis)
library(ggplot2)
library(latticeExtra)
library(sp)
library(raster)
library(rgdal)
library(tmap)
library(sf)
library(ggmap)
library(nnet)

nboot <- 500

```

## Parameter setting 

```{r}

moi <- c("May","June","July","August","September","October","November")
annees <- c(1993:2016)

```


                                                      ## SEASON FORECAST ##



```{r}

  load(file = file.path(dir_data, "extract", "lon.RData"))
  load(file = file.path(dir_data, "extract", "lat.RData"))


for (ind in 2:8){
  
    for (y in 1:nan){
    #---------------------------------------------------------------------------------------------------------------------------------------------
      ## we have to do a trick to find out the first bootstrapped iteration and the run index whithin this iteration matching the year we are interested in (the random sampling doesn't respect chronology)
      
       # bootstrap iteration index of the year selected
    load(file = file.path(dir_data, "extract", "years.RData")) # list of years in each bootstrap iteration
     
    list_match <- lapply(rand_year, function(x) which(y == x)) # list of matchs between list of years randomly generated for the bootstrap and the year we are interested in
     
     y_index <- list_match[[1]] # year index within the bootstrap iteration
     b_index <- 1 # bootstrap iteration index
     for (b in 1:(nboot-1)){ # pick the first iteration and first index matching the year we are looking for
       if (length(list_match[[b]])<1 & length(y_index)<1) {y_index <- list_match[[b+1]]; b_index <- b+1}
       else {y_index <- y_index; b_index <- b_index}
     }
    
    #---------------------------------------------------------------------------------------------------------------------------------------------
    ## loading dataframe of prevision with associated coordinates
  nom_ps <- paste0(indic[ind],b_index,"_seasquint_prev.RData")
  load(file = file.path(dir_data, "extract", nom_ps))
  ## creating a table containing most likely quintile and its associated confidence level (regarding probability value), with both coordinates (shape ready for shapefile conversion)

      matrix4shp <- matrix(0, nrow = ngrids, ncol = 4)
      for (i in 1:ngrids) {
        proba <- c(seasprob_ps[i,y_index[1],1], seasprob_ps[i,y_index[1],5]) # proba associated to each quintile 
        if (length(unique(proba))==2){
          quintile <- which.is.max(proba) # most likely quintile
          if (proba[quintile] > 0.30){ # likely quintile confidence
            matrix4shp[i,quintile] <- proba[quintile]
          }
        }
   }
    
    matrix4shp[,3] <- unlist(vect_lat)
    matrix4shp[,4] <- unlist(vect_lon)

    # We create a 3 layer-raster: 1st with grid ID (useless), 2nd with most likely quintile forecasted; 3rd with wilcoxon test outcomes. 
    
    # we load the dataframe previously built and transform it into a raster
    
    df_shp <- data.frame(matrix4shp)
    colnames(df_shp) <- c("quintile1", "quintile5","lat","lon")
    coordinates(df_shp) <- ~lon+lat
    proj4string(df_shp) <- CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
    shp_confprev <- st_as_sf(df_shp)
    ras_prev <- raster(shp_confprev)
    ext_prev <- extent(ras_prev)
    mask.raster <- raster(resolution=c(0.1,0.072), crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0", ## !!!!!!!!!!!
                          ext = ext_prev)
    ras_seas <- rasterize(shp_confprev, mask.raster) 
  
  # Stacking rasters from all the different months and saving it
  
  title <- paste0(indic[ind],"_prevquintseas", annees[y],".tif")
  writeRaster(ras_seas, filename=file.path(dir_plot, "season_raster", title), overwrite = TRUE)
  }
}
  
layername <- names(ras_seas)
save(layername, file = file.path(dir_plot, "season_raster", "layname_prevquint_seas.RData"))

```


