---
title: "prevision deteterministic skill"
output: html_document
---

```{r}
dir_data <- "D:/HOME/ekamir/scoring_medscope/data/season_trial2" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure" 
library(maps)
library(maptools)
library(rasterVis)
library(ggplot2)
library(latticeExtra)
library(sp)
library(raster)
library(rgdal)
library(tmap)
library(sf)
library(ggmap)
library(nnet)

```

## Parameter setting 

```{r}

moi <- c("May","June","July","August","September","October","November")
nscore <- 3

```
### MONTHLY ###

Building up rasters merging gridded MSESS score and statistical test - indicator and year specific


```{r}

for (ind in 1:2){
  
    ## loading dataframe of prevision with associated coordinates
  # 1=MSESS, 2=ACC prev, 3=ACC clim
  score_ps <- array(NA, dim=c(ngrids, nscore, ndimT, nboot)) 

  for (b in 1:nboot)  { 
  
    #for (e in 1:3){
  
    nom_prev <- paste0(indic[ind], b,"scoredetmonth_grid_prev.RData")
    load(file = file.path(dir_data, "score", nom_prev))

    score_ps[,,,b] <- det_month[,,]

    #}
  }
   
  load(file = file.path(dir_data, "extract", "lon.RData"))
  load(file = file.path(dir_data, "extract", "lat.RData"))
  
  matrix4shp <- matrix(0, nrow = ngrids, ncol = 4) # col: skill score, significant, lat, lon 
  
  matrix4shp[,3] <- unlist(vect_lat)
  matrix4shp[,4] <- unlist(vect_lon)

  
  ## creating a table containing mean skill and wilcoxon test outcome, with both coordinates (shape ready for shapefile conversion)
  ras_prev_complete <- list()
  for (t in 1:ndimT)  { 
    matrix4shp[,2] <- rep(0, ngrids)
    matrix4shp[,1] <- apply(score_ps[,1,t,], 1, mean, na.rm = TRUE) # select MSESS and summarize over bootstrap

  for (i in 1:ngrids)  { 
    
  wmsess <- wilcox.test(score_ps[i,1,t,], mu = 0, alternative = "greater", conf.level = 0.95)
  # wbia <- wilcox.test(x = abs(score_clim[i,t,2,]), y = score_ps[i,t,2,] ,alternative = "greater", paired = TRUE, conf.level = 0.95)
  # wrms <- wilcox.test(x = score_clim[i,t,3,], y = score_ps[i,t,3,] ,alternative = "greater", paired = TRUE, conf.level = 0.95)
 
    if (wmsess$p.value < 0.05) {
      
      matrix4shp[i,2] <- 1 
    }
  }
    
  # we load the dataframe previously built and transform it into a raster
  
  df_shp <- data.frame(matrix4shp)
  colnames(df_shp) <- c("score", "significance","lat","lon")
  coordinates(df_shp) <- ~lon+lat
  proj4string(df_shp) <- CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
  shp_scoredet <- st_as_sf(df_shp)
  ras_prev <- raster(shp_scoredet)
  ext_prev <- extent(ras_prev)
  mask.raster <- raster(resolution=c(0.1,0.072), crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0", ## !!!!!!!!!!!
                          ext = ext_prev)
  ras_prev_complete[[t]] <- rasterize(shp_scoredet, mask.raster)
  }
  
  # Stacking rasters from all the different months and saving it
  
  ras_month <- stack(ras_prev_complete)
  title <- paste0(indic[ind],"_detmonth.tif")
  writeRaster(ras_month, filename=file.path(dir_plot, "season_raster", title), overwrite = TRUE)
  
}
layername <- names(ras_month)
save(layername, file = file.path(dir_plot, "season_raster", "layname_detmonth.RData"))
```

### SEASONAL ###


```{r}

for (ind in 1:8){
  
    ## loading dataframe of prevision with associated coordinates
  # 1=MSESS, 2=ACC prev, 3=ACC clim
  score_ps <- array(NA, dim=c(ngrids, nscore, nboot)) 

  for (b in 1:nboot)  { 
  
    nom_prev <- paste0(indic[ind], b,"scoredetseas_grid_prev.RData")
    load(file = file.path(dir_data, "score", nom_prev))

    score_ps[,,b] <- det_seas[,]

  }
   
  load(file = file.path(dir_data, "extract", "lon.RData"))
  load(file = file.path(dir_data, "extract", "lat.RData"))
  
  matrix4shp <- matrix(0, nrow = ngrids, ncol = 4) # col: skill score, significant, lat, lon 
  
  matrix4shp[,3] <- unlist(vect_lat)
  matrix4shp[,4] <- unlist(vect_lon)

  
  ## creating a table containing mean skill and wilcoxon test outcome, with both coordinates (shape ready for shapefile conversion)

    matrix4shp[,2] <- rep(0, ngrids)
    matrix4shp[,1] <- apply(score_ps[,1,], 1, mean, na.rm = TRUE) # select MSESS and summarize over bootstrap

  for (i in 1:ngrids)  { 
    
  wmsess <- wilcox.test(score_ps[i,1,], mu = 0, alternative = "greater", conf.level = 0.95)
  # wbia <- wilcox.test(x = abs(score_clim[i,t,2,]), y = score_ps[i,t,2,] ,alternative = "greater", paired = TRUE, conf.level = 0.95)
  # wrms <- wilcox.test(x = score_clim[i,t,3,], y = score_ps[i,t,3,] ,alternative = "greater", paired = TRUE, conf.level = 0.95)
 
    if (wmsess$p.value < 0.05) {
      
      matrix4shp[i,2] <- 1 
    }
  }
    # We create a 3 layer-raster: 1st with grid ID (useless), 2nd with msess score; 3rd with wilcoxon test outcomes. 
    
    # we load the dataframe previously built and transform it into a raster
    df_shp <- data.frame(matrix4shp)
    colnames(df_shp) <- c("msess", "significance","lat","lon")
    coordinates(df_shp) <- ~lon+lat
    proj4string(df_shp) <- CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
    shp_det <- st_as_sf(df_shp)
    ras_prev <- raster(shp_det)
    ext_prev <- extent(ras_prev)
    mask.raster <- raster(resolution=c(0.1,0.072), crs = "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0", ## !!!!!!!!!!!
                          ext = ext_prev)
    ras_seas <- rasterize(shp_det, mask.raster) 
  
  # Stacking rasters from all the different months and saving it
  
  title <- paste0(indic[ind],"_detseas",".tif")
  writeRaster(ras_seas, filename=file.path(dir_plot, "season_raster", title), overwrite = TRUE)
  }

layername <- names(ras_seas)
save(layername, file = file.path(dir_plot, "season_raster", "layname_detseas.RData"))

```

