---
title: "score_proba"
output: html_document
67.26 sec elapsed
---

```{r setup, include=FALSE}
dir_data <- "D:/HOME/ekamir/scoring_medscope/data/season_trial2" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure"
library(easyVerification)
library(verification)
library(dplyr)
library(stats)
library(SpecsVerification)
library(s2dverification)
library(foreach)
library(iterators)
library(parallel)
library(doParallel)
no_core <- 5

```

## Loading latitude file

To be used for weighted aggregation.

```{r }
load(file = file.path(dir_data, "extract", "lat.RData"))
lati <- as.vector(vect_lat)

```


## Box-agregated scores

Aggregation computed using latitude weighting

```{r}
tictoc::tic()

for (ind in 1:8){
  scor_mont <- list()
  for (t in 1: ndimT){
    list_event <- list()
    for (e in 1:6){ #LT,MT,HT//LQ,MQ,HQ
      vect_boot <- vector()
      for(b in 1:1000){

      nom_ref <- paste0(indic[ind],b,"_bin_obs.RData")
      nom_prev <- paste0(indic[ind],b,"_prob_prev.RData")
     
      load(file = file.path(dir_data, "extract", nom_ref))
      load(file = file.path(dir_data, "extract", nom_prev))
    
      vect_boot[[b]] <- score_boite_prob(prob_ps, bin_ref, t, lati[,1], nb_bin = 5, e)$AUC
      }
      
    list_event[[e]] <- vect_boot
    }
    
  scor_mont[[t]] <- list_event
  }
  
  nom_ps <- paste0(indic[ind],"scorprob_box.RData")
  save(scor_mont, file = file.path(dir_data, "score", nom_ps))

}

tictoc::toc()

```
## Box-agregated score analysis

Aggregation computed using latitude weighting

```{r}

for (ind in 1:8){
  nom_ps <- paste0(indic[ind],"scorprob_box.RData")
  load(file = file.path(dir_data, "score", nom_ps))

  sum_df <- matrix(ncol = ndimT, nrow = 6)
  
  for (t in 1: ndimT){
    for (e in 1:6){ #LT,MT,HT//LQ,MQ,HQ
    sum_df[t,e] <- mean(scor_mont[[t]][[e]])

    }
  }
  
  nom_ps <- paste0(indic[ind],"scorprob_boxav.RData")
  save(sum_df, file = file.path(dir_data, "score", nom_ps))
}

nom_ps <- paste0(indic[ind],"scorprob_boxav.RData")
load(file = file.path(dir_data, "score", nom_ps))

```


## Gridded scores

Scores computed for each grid separately

```{r}
cl <- makeCluster(no_core)
registerDoParallel(cl)
tictoc::tic()
foreach(b=1:100, .packages = 'easyVerification') %dopar%  { # loop on bootstrap samples

  for (ind in 1:2){

  nom_ref <- paste0(indic[ind],b,"_ref.RData")
  nom_prev <- paste0(indic[ind],b,"_prev.RData")

  load(file = file.path(dir_data, "extract", nom_ref))
  load(file = file.path(dir_data, "extract", nom_prev))

  nom_probps <- paste0(indic[ind],b,"_prob_prev.RData")
  nom_obsbin <- paste0(indic[ind],b,"_bin_obs.RData")

  load(file = file.path(dir_data, "extract", nom_probps))
  load(file = file.path(dir_data, "extract", nom_obsbin))
  
  scoreprob_ps <- array (NA, dim=c(ngrids,ndimT,e))

  for (t in 1:ndimT){

     scoreprob_ps[,t,1] <- veriApply("EnsRoca", fcst=array_prev[,,,t], obs=array_obs[,,t], prob=1:2/3, parallel = TRUE)$cat1 
     scoreprob_ps[,t,2] <- veriApply("EnsRoca", fcst=array_prev[,,,t], obs=array_obs[,,t], prob=1:2/3, parallel = TRUE)$cat3 
     scoreprob_ps[,t,3] <- veriApply("EnsRoca", fcst=array_prev[,,,t], obs=array_obs[,,t], prob=1:4/5, parallel = TRUE)$cat1 
     scoreprob_ps[,t,4] <- veriApply("EnsRoca", fcst=array_prev[,,,t], obs=array_obs[,,t], prob=1:4/5, parallel = TRUE)$cat5
  
  }
  nom_prev <- paste0(indic[ind], b,"scoreprob_grid_prev.RData")

  save(scoreprob_ps, file = file.path(dir_data, "score", nom_prev))

}
}

stopCluster(cl)
tictoc::toc()



```
## Manual gridded scores

For ancillary checking

```{r}
nom_probps <- paste0(indic[ind],b,"_prob_prev.RData")
nom_obsbin <- paste0(indic[ind],b,"_bin_obs.RData")

load(file = file.path(dir_data, "extract", nom_probps))
load(file = file.path(dir_data, "extract", nom_obsbin))

  O=numeric(nb_bin)          # occurences bien prevues (hits)
  NO=numeric(nb_bin)         # fausses alertes
  HR=numeric(nb_bin)         # taux de bonnes previs agreges (pour ROC)
  FAR=numeric(nb_bin)        # taux de fausses alertes (pour ROC)
  HR_rel=numeric(nb_bin)     # taux bonnes previs par bin (pour diag fiabilite)
  F_rel=numeric(nb_bin)      # freq des previs pour chaque bin (pour diag fiabilite)

for (bin in (1:nb_bin)) {
    
        vect_prev <- prob_ps[i,,t,e]
        vect_obs <- bin_ref[i,,t,e]
        O[bin] = O[bin] + length(which(vect_prev>=((bin-1)/nb_bin) 
                                                           & vect_prev<(bin/nb_bin) & vect_obs==1))
        NO[bin] = NO[bin] + length(which(vect_prev>=((bin-1)/nb_bin) 
                                                             & vect_prev<(bin/nb_bin) & vect_obs==0))
        
}
  
for (bin in (1:nb_bin)) {
    # pour courbe ROC
    HR[bin] = sum(O[bin:nb_bin])/sum(O[])
    FAR[bin] = sum(NO[bin:nb_bin])/sum(NO[])
  }
  # taux par bin (pour diag de fiabilite)
  HR_rel=O/(O+NO)
  F_rel=(O+NO)/sum(O[]+NO[])
  
  # calcul AUC (cf http://stackoverflow.com/questions/4954507/calculate-the-area-under-a-curve-in-r)
  AUC=-sum(diff(FAR) * (head(HR,-1)+tail(HR,-1)))/2
  
  liste_score = list(HR=HR,FAR=FAR, HR=HR, FAR=FAR, AUC=AUC)

```





