---
title: "Determinist scores"
output: html_document
---

```{r setup, include=FALSE}
dir_data <- "D:/HOME/ekamir/scoring_medscope/data/season" 
dir_plot <- "D:/HOME/ekamir/scoring_medscope/figure"
library(dplyr)
library(tidyverse)
library(plyr)
library(easyVerification)
library(verification)
library(foreach)
library(iterators)
library(parallel)
library(doParallel)
library(readr)
no_core <- 6
nboot <- 100
month <- 4:6

```
## Computing grid scores and saving them in arrays called "det_"

```{r setup, include=FALSE}
#
tictoc::tic()
acc_prev <- vector()
acc_clim <- vector()
msess <- vector()

for (ind in c(2,3,4,8)){
   # require(doSNOW)
   # registerDoSNOW(makeCluster(2, type = "SOCK"))

  # , .verbose = T
cl <- makeCluster(no_core)
registerDoParallel(cl)
#registerDoSNOW(cl)

foreach(b=1:nboot, .packages=c('easyVerification', 's2dverification')) %dopar%  { # loop on bootstrap samples
#Spearman <- easyVerification:::EnsCorr
  
  nom_ref <- paste0(indic[ind],b,"_ref.RData")
  nom_prev <- paste0(indic[ind],b,"_prev.RData")
  nom_clim <- paste0(indic[ind],b,"_clim.RData")
  nom_an_prev <- paste0(indic[ind],b,"_anomaly_prev.RData")
  nom_an_obs <- paste0(indic[ind],b,"_anomaly_obs.RData")
  
  load(file = file.path(dir_data, "extract", nom_ref))
  load(file = file.path(dir_data, "extract", nom_prev))
  load(file = file.path(dir_data, "extract", nom_clim))
  load(file = file.path(dir_data, "extract", nom_an_prev))
  load(file = file.path(dir_data, "extract", nom_an_obs))
  
  # ensemble mean 
  # prev_mean <- apply(array_prev, c(1,2,4), mean)
  # clim_mean <- apply(array_clim, c(1,2,4), mean)

  ### Score computing: We compute bias, and cross validated rmse and correlation coefficient.
  
      ### MONTHLY ###
  
  # det_month <- array(NA, dim = c(ngrids,2,ndimT))
  # 
  # for (t in 1:ndimT){ 
  #   
  #   # MSESS
  #   
  # msess <- veriApply("EnsMsess", fcst=t(prev_mean[,,t]), fcst.ref=t(clim_mean[,,t]), obs=t(array_obs[,,t]), parallel = TRUE)
  # 
  #  # ACC #
  #   
  #     # Pearson for continued indicators
  #   #if (ind!=3 & ind!=4 & ind!=5) { 
  #     # ref vs prev
  #   acc_prev <- veriApply("EnsCorr", fcst=prev_anomaly[,,,t], obs=obs_anomaly[,,t], parallel = TRUE)
  #     # ref vs clim
  # 
  #   # } else { # Spearman for ordinal indicators
  #   #   Spearman <- s2dverification:::.Corr
  #   #   # ref vs prev
  #   # acc_prev <- veriApply("Corr", fcst=clim_anomaly[,,,t], obs=clim_anomaly[,,,t],  posloop = 2,)$corr
  #   #   # ref vs clim
  #   # acc_clim <- veriApply("Corr", fcst=clim_anomaly[,,,t], obs=obs_anomaly[,,t], parallel = TRUE)$corr
  #   #   
  #   # }
  # 
  # det_month[,,t] <- array(c(msess, acc_prev), dim=c(ngrids,2))
  # 
  # }
  
      ### SEASONAL ###
  
  det_seas <- array(NA, dim = c(ngrids,2))

  prev_seas <- apply(array_prev[,,,month], c(1,2,3), sum)
  clim_seas <- apply(array_clim[,,,month], c(1,2,3), sum)
  ref_seas <- apply(array_obs[,,month], c(1,2), sum)
  
  # prev_seas_mean <- apply(prev_seas, c(1,2), mean)
  # clim_seas_mean <- apply(clim_seas, c(1,2), mean)
  
    # MSESS
    
  msess <- veriApply("EnsMsess", fcst=prev_seas, fcst.ref=clim_seas, obs=ref_seas, parallel = TRUE)

    # ACC #
    
      # Pearson for continued indicators
        #if (ind!=3 & ind!=4 & ind!=5) { 
      # ref vs prev
  acc_prev <- veriApply("EnsCorr", fcst=prev_anomaly, obs=obs_anomaly)
      # ref vs clim

    #     } else { # Spearman for ordinal indicators
    #       Spearman <- s2dverification:::.Corr
    #   # ref vs prev
    # acc_prev <- veriApply("Corr", fcst=anoprev_seas, obs=anoref_seas, parallel = TRUE)$corr
    #   # ref vs clim
    # acc_clim <- veriApply("Corr", fcst=anoclim_seas, obs=anoref_seas, parallel = TRUE)$corr
    #    
    # }
    
  det_seas <- array(c(msess, acc_prev), dim=c(ngrids,2))
  
  nom_prevmonth <- paste0(indic[ind], b,"scoredetmonth_grid_prev.RData")
  nom_prevseas <- paste0(indic[ind], b,"scoredetseas_grid_prev.RData")

  #save(det_month, file = file.path(dir_data, "score", nom_prevmonth))
  save(det_seas, file = file.path(dir_data, "score", nom_prevseas))

  #gc(TRUE)

}
stopCluster(cl)

}
tictoc::toc() 

```

## Box scores 

We aggregate gridded deterministic scores with latitude weighting.

```{r setup, include=FALSE}

load(file = file.path(dir_data, "extract", "lat.RData"))
lati <- as.vector(vect_lat)
coeff <- vector()
month_ps <- matrix(ncol = 2, nrow = 6)
seas_ps <- matrix(ncol = 2, nrow = 1)

for (ind in c(2,3,4,8)){
boot_month <- list()
boot_seas <- list()

for(b in 1:nboot)   {
  # loading gridded scores

  # seasonal
  nom_prevseas <- paste0(indic[ind], b,"scoredetseas_grid_prev.RData")
  load(file = file.path(dir_data, "score", nom_prevseas))


  # monthly
  # if (ind!=3 & ind!=4 & ind!=5) {
  #    box_prev_month <- matrix(nrow = ndimT, ncol = 3)
  #   nom_prevmonth <- paste0(indic[ind], b,"scoredetmonth_grid_prev.RData")
  #   load(file = file.path(dir_data, "score", nom_prevmonth))
  # 
  #   for (t in 1:ndimT){
  #     # box aggregation with latitude weighting
  #     val_prevmonth <- list()
  # 
  #     for (i in 1:ngrids){
  #       val_prevmonth[[i]] <- det_month[i,,t]*cos(pi*lati[i,1]/180)
  #       coeff[i] <- cos(pi*lati[i,1]/180)
  #       # removing NAs
  #       if (length(which(is.na(det_month[i,,t])))>0){
  #         coeff[i] <- NA
  #         val_prevmonth[[i]] <- rep(NA,3)
  #       }
  # 
  #     }
  # 
  #     box_prev_month[t,] <- apply(array(unlist(val_prevmonth) , c(3,ngrids)), 1, sum, na.rm = T)/sum(coeff, na.rm = T)
  #     #box_prev_month[t,] <- Reduce("+", val_prevmonth)/sum(coeff)
  # 
  #   }
  #   boot_month[[b]] <- box_prev_month
  #}
  # seasonal
  val_prevseas <- list()

  for (i in 1:ngrids){
    val_prevseas[[i]] <- det_seas[i,]*cos(pi*lati[i,1]/180)
    coeff[i] <- cos(pi*lati[i,1]/180)
    # removing NAs
    if (length(which(is.na(det_seas[i,])))>0){
      coeff[i] <- NA
      val_prevseas[[i]] <- rep(NA,2)
    }
  }

  boot_seas[[b]] <- apply(array(unlist(val_prevseas) , c(2,ngrids)), 1, sum, na.rm = T)/sum(coeff, na.rm = T)
}

  # if (ind!=3 & ind!=4 & ind!=5) {
  # month_ps <- apply(array(unlist(boot_month) , c(6,3,nboot)), c(1,2), mean)
  # colnames(month_ps) <- c("MSESS","ACC_ps","ACC_clim")
  # nom_psmonth <- paste0(indic[ind], "monthdet_box_prev.csv")
  # write_csv(as.data.frame(month_ps), file.path(dir_data, "score", nom_psmonth))
  # }
  
  nom_psseas <- paste0(indic[ind], "seasdet_box_prev.csv")
  seas_ps <- apply(array(unlist(boot_seas) , c(2,nboot)), 1, mean, na.rm=T)
  write_csv(as.data.frame(seas_ps), file.path(dir_data, "score", nom_psseas))

}

```


